### PR TITLE
Create story-time-solid.md

### PR DESCRIPTION
**Pull request by lukaseppler**

### CODE REVIEW

**Review by andyundso — COMMENTED** [review]
I personally do not like this. I don't think this adds anything interesting to the blog, besides that ChatGPT can write below-average novels.

I did not further check if the generated content is correct. However, if it is decided that this post should be published, I would recommend to do so.

It is up to @tizpuppi , @Zinggi and @Myrthi74 if this should go live, as their names are used.

**Comment by lukaseppler** [comment]
I agree, nothing high-brow. But I think it's fun and actually quite smart, for people who don't know how we work.

**Comment by Zinggi** [comment]
Like @andyundso, I don't think we should publish anything from ChatGPT directly.  

I stopped reading after a bit because it's the typical ChatGPT style and there is no interesting content in it.

**Comment by lukaseppler** [comment]
So what's the verdict? I'm not publishing this blog post?

**Comment by Zinggi** [comment]
> So what's the verdict? I'm not publishing this blog post?

Yes, for me it's a NO. I don't want to be in a ChatGPT fan fiction

**Pull request closed without merging**
